import type { InferSelectModel } from "drizzle-orm";
import type { dailySnapshots, users } from "@/db/schema";

type Snapshot = InferSelectModel<typeof dailySnapshots>;
type User = InferSelectModel<typeof users>;

function formatDuration(sec: number | null | undefined): string {
  if (sec == null || !Number.isFinite(sec)) return "—";
  const mins = Math.round(sec / 60);
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
}

function formatTime(ts: Date | string | null | undefined): string {
  if (!ts) return "—";
  const d = typeof ts === "string" ? new Date(ts) : ts;
  if (Number.isNaN(d.getTime())) return "—";
  return d.toISOString().slice(11, 16) + "Z";
}

function pct(partSec: number | null | undefined, totalSec: number | null | undefined): string {
  if (partSec == null || totalSec == null || totalSec <= 0) return "—";
  return ((partSec / totalSec) * 100).toFixed(1);
}

export function generateDailyMarkdown(user: User | null, snapshot: Snapshot): string {
  const name = user?.name || user?.email || "User";
  const d = String(snapshot.date);

  return `# Health Report — ${d}
**Generated by Health OS** · ${name}

---

## 📊 Daily Scores
| Metric | Score |
|--------|-------|
| Sleep | ${snapshot.sleepScore ?? "—"}/100 |
| Readiness | ${snapshot.readinessScore ?? "—"}/100 |
| Activity | ${snapshot.activityScore ?? "—"}/100 |
| HRV | ${snapshot.hrv ?? "—"}ms |

---

## 😴 Sleep Analysis
- **Total Sleep**: ${formatDuration(snapshot.sleepDuration)}
- **Time in Bed**: ${formatDuration(snapshot.timeInBed)}
- **Efficiency**: ${snapshot.efficiency ?? "—"}%
- **Latency**: ${snapshot.latency ?? "—"} minutes to fall asleep
- **Bedtime**: ${formatTime(snapshot.bedtimeStart)}
- **Wake time**: ${formatTime(snapshot.bedtimeEnd)}

### Sleep Stages
| Stage | Duration | % of Sleep |
|-------|----------|------------|
| Deep | ${formatDuration(snapshot.deepSleep)} | ${pct(snapshot.deepSleep, snapshot.sleepDuration)}% |
| REM | ${formatDuration(snapshot.remSleep)} | ${pct(snapshot.remSleep, snapshot.sleepDuration)}% |
| Light | ${formatDuration(snapshot.lightSleep)} | ${pct(snapshot.lightSleep, snapshot.sleepDuration)}% |

### Sleep Quality Metrics
- **Restfulness**: ${snapshot.restfulness ?? "—"}/100
- **Timing**: ${snapshot.timing ?? "—"}/100
- **Lowest heart rate**: ${snapshot.lowestHeartRate ?? "—"}bpm
- **Average breathing rate**: ${snapshot.averageBreath ?? "—"} breaths/min

---

## ⚡ Readiness Contributors
| Factor | Score |
|--------|-------|
| HRV Balance | ${snapshot.hrvBalance ?? "—"}/100 |
| Recovery Index | ${snapshot.recoveryIndex ?? "—"}/100 |
| Resting HR | ${snapshot.restingHeartRateScore ?? "—"}/100 |
| Body Temperature | ${snapshot.bodyTemperatureScore ?? "—"}/100 |
| Sleep Balance | ${snapshot.sleepBalance ?? "—"}/100 |
| Activity Balance | ${snapshot.activityBalance ?? "—"}/100 |
| Previous Night | ${snapshot.previousNightScore ?? "—"}/100 |
| Previous Day Activity | ${snapshot.previousDayActivity ?? "—"}/100 |

**Body Temperature Deviation**: ${snapshot.bodyTempDeviation ?? "—"}°C from baseline

---

## 🏃 Activity
- **Steps**: ${snapshot.steps?.toLocaleString() ?? "—"}
- **Active Calories**: ${snapshot.activeCalories ?? "—"} kcal
- **Total Calories**: ${snapshot.totalCalories ?? "—"} kcal
- **Distance**: ${snapshot.walkingDistance != null ? (snapshot.walkingDistance / 1000).toFixed(1) : "—"}km
- **High Activity Time**: ${formatDuration(snapshot.highActivityTime)}
- **Sedentary Time**: ${formatDuration(snapshot.sedentaryTime)}
- **Inactivity Alerts**: ${snapshot.inactivityAlerts ?? "—"}

---

*Report generated by Health OS · ${new Date().toISOString()}*
*Data sourced from Oura Ring API*
`;
}
